### ISSUE TITLE
Dashboard's UI design size

### ISSUE THREAD

**Issue by JohnPixle** [udacity/challenge-4#3]
Hi there, I am very much interested in exploring this project and contribute. 
I am a UI/UX designer with a huge interest in next generation cognitive technology UIs and this project sounds very inspiring.

I would like to ask a couple of technical questions before I dive into this.

**UI design dimensions**
Judging from the Sketch file, each dashboard screen has the dimensions of 1636 x 1130. Are these the dimensions that correspond to the real tablet/UI ? Are these dimensions the boundaries of the design?

**Is this Challenge design-only?**
Just to confirm that this project is strictly for UI/UX purposes and that wiring up the interface is a separate project/app.

Thanks for your time.
John

**Comment by baumanab** [comment]
Thank you for these questions, sorry for the very late response.  Closing since the challenge is over.
